plex:
  url: http://192.x.xx.xx:32400
  x-token: xxxxyyy
  library: libraryName

user:
  folder_to_watch: /home/user # Point to docker internal directory if using docker
  extension_to_watch:
    - .ass
    - .srt
    - .vtt