version: "3"
services:
  app:
    image: wanhuz/plex-metadata-refresher
    container_name: plex-metadata-refresher
    restart: unless-stopped
    volumes:
      - /path/to/config.yaml:/usr/src/app/config.yaml
      - /path/to/plex/media:/target/directory/in/config
    environment:
      - PYTHONUNBUFFERED=1 # Print output to docker logs